version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/development/api/Dockerfile
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - daily-hussle-api

  postgres-db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - daily-hussle-api

networks:
  daily-hussle-api:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
