name: CI

on:
  push:
    branches: [master]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build_and_push:
    name: Login to digital ocean droplet and build the container
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Login
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          script: |
            docker-compose up --build -d
